#!/bin/bash
# ASUVPN - EASY VPN with VPNBOOK.COM

YELLOW='\033[1;33m'
RESET='\033[0m'
TMOUT=10

if [[ $(sudo -vn 2>&1) == "Sorry, user $(whoami) may not run sudo on $(hostname -s)." ]]; then
  echo -e "You don't have ${YELLOW}sudo${RESET} rights"
  echo -e "Please run this script as ${YELLOW}root${RESET} or with ${YELLOW}sudo${RESET} rights"
  exit 1
fi

if [ $(which unzip) -z ] 2> /dev/null; then
  echo -e "To run this script ${YELLOW}unzip${RESET} must be installed"
  echo -e "Debian/Ubuntu use: ${YELLOW}apt-get install unzip${RESET}"
  echo -e "CentOS/Fedora use: ${YELLOW}yum install unzip${RESET}"
  exit 2
fi

if [ $(which openvpn) -z ] 2> /dev/null; then
  echo -e "To run this script ${YELLOW}OpenVPN${RESET} must be installed!"
  echo -e "Debian/Ubuntu use: ${YELLOW}apt-get install openvpn${RESET}"
  echo -e "CentOS/Fedora use: ${YELLOW}yum install openvpn${RESET}"
  exit 3
fi

url='http://www.vpnbook.com/free-openvpn-account/VPNBook.com-OpenVPN-'
conf='VPNBook.com-OpenVPN-'
prc=${YELLOW}'Downloading and Extracting config file...'${RESET}
passfile='/tmp/vbpassword.tmp'

echo -e "\n${YELLOW}Connecting to www.vpnbook.com...${RESET}"
wget -q -O /tmp/vpnbook.tmp www.vpnbook.com/freevpn
username=$(grep -m 1 -oP "(?<=<li>Username: <strong>)[[:graph:]]+(?=</strong></li>)" /tmp/vpnbook.tmp)
password=$(grep -m 1 -oP "(?<=<li>Password: <strong>)[[:graph:]]+(?=</strong></li>)" /tmp/vpnbook.tmp)
echo -e "$username\n$password" > "$passfile"
rm /tmp/vpnbook.tmp

echo -e " --------------------------------------------"
echo -e " Username: ${YELLOW}$username${RESET}"
echo -e " Password: ${YELLOW}$password${RESET}"
echo -e " --------------------------------------------"
echo "Choose your VPN Server connection destination: "
PS3='Please enter your choice: '
select opt in USA1 USA2 CANADA EUROPE1 EUROPE2 GERMANY Quit
do
  case $opt in
    "USA1") sv=("US1.zip" "USA1" "us1") ;;&
    "USA2") sv=("US2.zip" "USA2" "us2") ;;&
    "CANADA") sv=("CA1.zip" "CANADA" "ca1") ;;&
    "EUROPE1") sv=("Euro1.zip" "EUROPE1" "euro1") ;;&
    "EUROPE2") sv=("Euro2.zip" "EUROPE2" "euro2") ;;&
    "GERMANY") sv=("DE1.zip" "GERMANY" "de233") ;;&
    "USA"* | "CAN"* | "EUR"* | "GER"*) break ;;
    "Quit") echo -e "\nExiting...\n"; exit 0 ;;
    *) echo Invalid option, try again. ;;
  esac
done

if [[ -z $opt ]]; then
  opt=$[ ( $RANDOM % 6 ) + 1 ]
  case $opt in
    1) sv=("US1.zip" "USA1" "us1") ;;
    2) sv=("US2.zip" "USA2" "us2") ;;
    3) sv=("CA1.zip" "CANADA" "ca1") ;;
    4) sv=("Euro1.zip" "EUROPE1" "euro1") ;;
    5) sv=("Euro2.zip" "EUROPE2" "euro2") ;;
    6) sv=("DE1.zip" "GERMANY" "de233") ;;
  esac
  opt=$[ ( $RANDOM % 4 ) + 1 ]
  case $opt in
    1) pr="tcp80" ;;
    2) pr="tcp443" ;;
    3) pr="udp53" ;;
    4) pr="udp25000" ;;
  esac
else
  TMOUT=0
  echo -e "\nChoose VPN Server port number:"
  select opt in "TCP Port 80" "TCP Port 443" "UDP Port 53" "UDP Port 25000" Quit
  do
    case $opt in
      "TCP Port 80") pr="tcp80" ;;&
      "TCP Port 443") pr="tcp443" ;;&
      "UDP Port 53") pr="udp53" ;;&
      "UDP Port 25000") pr="udp25000" ;;&
      "TCP"* | "UDP"*) break ;;
      "Quit") echo -e "\nExiting...\n"; exit 0 ;;
      *) echo Invalid option, try again. ;;
    esac
  done
fi

if [ "$opt" != "Quit" ]; then
  ovpn='/tmp/vpnbook-'${sv[2]}'-'${pr}'.ovpn'
  echo -e "\n${YELLOW}Connecting to ${sv[1]} VPN server...${RESET}"
  cd /tmp
  echo -e $prc
  wget -q -nv ${url}${sv[0]} && unzip -qq ${conf}${sv[0]}
  echo -e "\nauth-user-pass $passfile\nauth-nocache" >> $ovpn
  if [ "$EUID" -ne 0 ]; then
    sudo openvpn $ovpn
  else
    openvpn $ovpn
  fi
fi
